### ISSUE TITLE
JS / CSS not automatically included from YAML files

### ISSUE THREAD

**Issue by mrjmd** [mrjmd/pdb#11]
Our YAML files for components have sections like this:

add_js:
&nbsp;&nbsp;header:
&nbsp;&nbsp;footer:
add_css:
&nbsp;&nbsp;header:
&nbsp;&nbsp;footer:

But right now these don't actually do anything. That's no good.

**Comment by mark-casias** [comment]
I don't think we need these. These are per instance js / css.. unless we want to define some default layout stuffs.

**Comment by mrjmd** [comment]
I don't think I follow your comment... these are component-specific js and css includes, which have lots of use cases and are the main way to add css and js to your component in the Drupal 7 version. 

The only reason they aren't being used currently is because Angular 2 components are adding their typescript files and css files directly, which is actually problematic for several reasons (we should be compiling typescript into js, Drupal is not aware of these files for cache busting, etc).

So I think this is absolutely needed.

**Comment by mrjmd** [comment]
This is merged, thanks!
