### ISSUE TITLE
PDB Extension Scanner needs improvements

### ISSUE THREAD

**Issue by derekreesemediacurrent** [mrjmd/pdb#19]
Update PDB Extension Discovery Mechanism to support scanning configurable directories.

Currently the module is hardcoded to scan 'modules/pdb' but will need to be configurable by users in GUI and drush and should support whatever string the module name is, as well as legacy directories by default.

**Comment by derekreesemediacurrent** [comment]
#### Acceptance Criteria
Users can configure the scan directories, and the default directories are based on the module name and include the module directory as well as the legacy ('sites/all') directory.

#### Technical Requirements
We need to update the scan function to use correct defaults along with a user-configured variable. In addition, we need to build an admin config form to allow these settings to be configured.

#### Links
/admin/structure/block/list
/admin/config/pdb (TBD)

**Comment by mrjmd** [comment]
Just to make sure we're aligned on this, as of right now when you turn on the main module, all components appear even if you don't have on the Angular 2 or React sub-modules. This is no good.

I went ahead and updated the requirements and title of this ticket to reflect that.

**Comment by derekreesemediacurrent** [comment]
Now tracking here, in component_api: https://github.com/mrjmd/component_api/issues/1
