### ISSUE TITLE
Better Angular 2 example component

### ISSUE THREAD

**Issue by mrjmd** [mrjmd/pdb#20]
One of our overarching goals in the run-up to DrupalCon is to be able to publicly showcase this module. This will most likely be done using the Angular 2 sub-module since it has the most active development behind it.

However, the example components currently available are lackluster, and we should try to get one decent looking component with some more advanced ng2 behaviors out there for people to see.

**Comment by pxwise** [comment]
http://todomvc.com/ is the gold standard for Hello Worlding a js framework.

May not be flashy enough for a showcase, but worth considering as a default demo per framework.

**Comment by mrjmd** [comment]
Copying comment from duplicate issue:

We need a "flashy" Showcase component for Drupalcon.

My first thought is to build something demoing a reusable angular component and two way data binding at the same time.

I'm looking at building a panels IPE inspired set of fields with http://valor-software.com/ng2-dragula/index.html

**Comment by mrjmd** [comment]
Closing this as no longer relevant.
