### ISSUE TITLE
Update readme.md to conform to d.o standards

### ISSUE THREAD

**Issue by derekreesemediacurrent** [mrjmd/pdb#40]
See standards at https://www.drupal.org/node/2181737

Mostly so we don't get complaints in the project review queue...

...also, you know, for readability and good documentation porpoises 🐬

**Comment by derekreesemediacurrent** [comment]
PR: https://github.com/mrjmd/pdb/pull/42

**Comment by mrjmd** [comment]
The new readme is looking good, thanks for the help.
