### ISSUE TITLE
Fix Notice of undefined constant DRUPLA_NO_CACHE

### ISSUE THREAD

**Issue by kepford** [mrjmd/pdb#48]
Notice: Use of undefined constant DRUPAL_NO_CACHE - assumed 'DRUPAL_NO_CACHE' in Drupal\pdb\Plugin\Derivative\PdbBlockDeriver->getDerivativeDefinitions() (line 52 of modules/pdb/src/Plugin/Derivative/PdbBlockDeriver.php).

**Comment by kepford** [comment]
Block cache API was removed.
https://www.drupal.org/node/2158003

**Comment by mrjmd** [comment]
Merged, thanks Bob.
