### ISSUE TITLE
Make component API a separate module?

### ISSUE THREAD

**Issue by mrjmd** [mrjmd/pdb#5]
The core functionality here is: creating component directories containing css, js, markup template, and yaml files containing metadata about them. Then having Drupal walk these directories and ingest the metadata.

This has applications beyond just decoupled blocks, for example integration with Kalastatic rapid prototyping and living style guide tool: https://github.com/kalamuna/kalastatic/wiki

I think it's worth exploring making this a common API module that we use for our blocks.

**Comment by mrjmd** [comment]
I'm going to give this a shot over the weekend.

**Comment by mrjmd** [comment]
Repo for this work is here: https://github.com/mrjmd/component_api

Note this is not working and we have not removed the code from this repo or added the dependency yet.

**Comment by derekreesemediacurrent** [comment]
WIP Branches:
https://github.com/derekreesemediacurrent/pdb/tree/PDB-5--component-api
https://github.com/derekreesemediacurrent/decoupled-blocks-drupal-vm/tree/PDB-5--component-api
https://github.com/derekreesemediacurrent/component_api/tree/8.x-1.x

Will PR when component_api has MVP of functional equivalency with current PDB Extension Discovery.

**Comment by derekreesemediacurrent** [comment]
PDB Extension Discovery was removed in https://github.com/mrjmd/pdb/pull/34

We're discussing a few other items to abstract into component API, such as Form API YML and possibly some sort of library auto-discovery.

**Comment by mrjmd** [comment]
First iterations of both items @derekreesemediacurrent mentioned above are integrated now:

- Form API YAML from PR #46.
- Library auto-discovery from #45.

**Comment by mrjmd** [comment]
There is a bunch of core conversation work happening around very similar efforts, as well as other contrib projects. We are working to dovetail these efforts into a single solution.

See also:
https://www.drupal.org/node/2702061
https://www.drupal.org/project/components
https://www.drupal.org/project/componentize
http://www.marcdrummond.com/posts/2016/03/25/drupal-front-end-future

**Comment by mrjmd** [comment]
We had a bunch of conversations about all this over DrupalCon New Orleans last week. Core is definitely heading in this direction, and what they are trying to do is really ambitious and exciting.

However, I think for now Decoupled Blocks should just keep doing what we're doing. I'll stay in conversation with Wim Leers, John Albin, Marc Drummond etc., but until this lands in core our current solution is fine and we can just leave it in this module instead of worrying about abstracting.

Marking wontfix for now.
