### ISSUE TITLE
Add Base Directory to systemConfig.js

### ISSUE THREAD

**Issue by tesliker** [mrjmd/pdb#53]
Line 53 of systemConfig.js hard codes the path to the app. We need to add drupal settings base directory instead of assuming the project lives in the root directory, otherwise users will get 404 errors for any JS files called from angular.

**Comment by tesliker** [comment]
FYI This can be assigned to me.

**Comment by mrjmd** [comment]
This ended up being handled in [#60] and its associated PR, closing this.
