### ISSUE TITLE
Map.app definition is hard-coded within Config variable [pdb_ng2 - assets/app/systemConfig.js]

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#60]
## Motivation
I downloaded project and started to work with, then I noticed it wasn't working, then I tracked until I found "**app.ts**" wasn't loaded because server returned 404 error.

I found "**_config_**" variable has defined map attribute with app path to a hard-coded relative location, my contributed modules are stored inside a "**contrib**" subfolder within root **/modules** folder,
![config__map_hardcoded](https://cloud.githubusercontent.com/assets/3356086/15277519/7ce5eb5e-1ac4-11e6-8fe5-0162695b71d8.png)

Then I defined path properly, and now ng2 is throwing me a lot of error messages, it looks like it is not founding templates file as well,
![ng2](https://cloud.githubusercontent.com/assets/3356086/15277529/ba3c7568-1ac4-11e6-8c44-90d03bc93230.png)

It looks like "**Components**" has hard-coded URL to templates and styles files,
![component--ng2](https://cloud.githubusercontent.com/assets/3356086/15277536/ff5ebc0a-1ac4-11e6-894b-9eff443e9ca9.png)

## Propose Solution
Those paths should be defined on PHP and send to "**drupalSettings**" object to javascript, we could use the following method inside "_Ng2Block_" block plugin,
`public function attachSettings(array $component)`

To define those values, this function [drupal_get_path](https://api.drupal.org/api/drupal/core%21includes%21bootstrap.inc/function/drupal_get_path/8.2.x) could helps.

If you don't mind, I would do a **Pull Request**, then y'all could check it. Let me know your thoughts,

**Comment by kenneth-bolivar-castro** [comment]
@mrjmd I think, you're in charge, I just created a pull request, let me know your thoughts,

**Comment by mrjmd** [comment]
Thanks for you help on this @kenneth-bolivar-castro! Merged :)
