### ISSUE TITLE
Decoupled Blocks VM

### ISSUE THREAD

**Issue by mark-casias** [mrjmd/pdb#7]
Fork DrupalVM and make in install this module by default.

**Comment by mark-casias** [comment]
Forked the original DrupalVM repository and update the example configuartion files. Ready for others to test and submit PR's against: https://github.com/mark-casias/decoupled-blocks-drupal-vm

**Comment by mark-casias** [comment]
need to update documentation for install
need to revert to 8.0.x

**Comment by mrjmd** [comment]
This is working fine, any remaining issue should be filed to the VM repo above.
