### ISSUE TITLE
pdb.ng2.config library dependency typo

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#72]
Drupal throws an error messages related with a theme missing from file system: pdn_ng2,
![pdn_ng2--library](https://cloud.githubusercontent.com/assets/3356086/15972151/ff570f84-2ef9-11e6-906b-9e99e00d5c55.png)

I debugged and I found a typo into "_pdb_ng2.libraries.yml_" file at line 42,
https://github.com/mrjmd/pdb/blob/8.x-1.x/modules/pdb_ng2/pdb_ng2.libraries.yml#L42

It defines a dependency that doesn't exist, it should be "**pdb_ng2**".

**Comment by mrjmd** [comment]
Fixed, thanks!
