### ISSUE TITLE
Expose configuration routing into pdb_ng2 module

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#74]
I think, it could be great access to admin configuration page from "Extend" page, once we enable "pdb_ng2" module, it should looks like this:
![pdb_ng2--admin-page](https://cloud.githubusercontent.com/assets/3356086/15973331/1bc4ebe0-2f00-11e6-8f86-d50fe499a902.png)

**Comment by mrjmd** [comment]
Merged, thanks!
