### ISSUE TITLE
PdbBlock::createElementsFromConfiguration undefined index "pdb_configuration"

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#76]
As soon as we place any Angular2 block to any region, site throws the following warning: 
![createelementsfromconfiguration](https://cloud.githubusercontent.com/assets/3356086/15974055/be90f096-2f03-11e6-92ac-00d8d4717dc7.png)

We should check that "pdb_configuration" exists before use it,
https://github.com/mrjmd/pdb/blob/8.x-1.x/src/Plugin/Block/PdbBlock.php#L242

**Comment by mrjmd** [comment]
Looks good. Merged, thanks!
