### ISSUE TITLE
pdb_ng2 - Allow ngClassName definition by YAML file

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#83]
Since we will allow developer to define path to component, those file name or even machine name won't match with current "**ngClassName**", then I propose a new key to setup this value into YAML file,
```
name: NG2 Example
machine_name: ng2-example-1
ng_class_name: Ng2ExampleApp
type: pdb
description: 'NG 2 Example Component 1'
package: NG2
version: '1.0.0'
core: '8.x'
module_status: active
presentation: ng2
path: modules/contrib/pdb/modules/pdb_ng2/components/ng2_example/ng2-example.component
```
Then we could inject that value into "**Ng2Block::attachSettings**" method,
```
// Check if ng_class_name was defined.
if(!empty($component['ng_class_name'])) {
  // Add "ngClassName" value.
 $attached['drupalSettings']['pdb']['ng2']['components']['instance-id-' . $uuid] += [
    'ngClassName' => $component['ng_class_name'],
 ];
}
```

It mean, we can have access that value before load component within "**ScrollLoader**" typescript class:
```
// Define ngClassName based on component settings or build default ngClassName based on element value.
let ngClassName = (typeof this.components[id]["ngClassName"] === 'string') ?
this.components[id]["ngClassName"] : this.convertToNgClassName(this.components[id]["element"]);
```
It will give us more flexibility when Angular developer are working, avoiding a new convention name for their components.

**Comment by mrjmd** [comment]
Merged.

We will need to make more improvements to the class name logic soon to get offline template compiling to work, since the component factory files have classnames that are dynamically generated. But this step opens up more flexibility. Thanks!
