### ISSUE TITLE
Example blocks not appearing as available if module installed in a subfolder

### ISSUE THREAD

**Issue by shrop** [mrjmd/pdb#86]
I was not able to get to the example blocks from the Drupal core blocks UI. @mrjmd asked where I had the pdb module installed as he knew this could be an issue. Turns out that the example blocks are not picked up when the module is installed in a subfolder under `modules` (ex: `modules/contrib/pdb`). The example blocks do show find if installed directly under `modules` (ex: `modules/pdb`)

* Used core theme
* Installed in `modules/contrib/pdb`
* On branch `feature/ng-prime` and `8.x-1.x`
* `npm install` was run in `modules/pdb/modules/pdb_ng2`
* Ran `tsc` in `modules/pdb/modules/pdb_ng2`

**Comment by mrconnerton** [comment]
I just did a fresh install of the alpha4 and latest version of d8 and this seems to be resolved.

**Comment by mrjmd** [comment]
Closing this out as fixed in latest version.
