### ISSUE TITLE
npm installation error for angular2

### ISSUE THREAD

**Issue by narasing494599** [mrjmd/pdb#89]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm ERR! fetch failed https://registry.npmjs.com/yargs-parser/-/yargs-parser-2.4
.1.tgz
npm WARN retry will retry, error on last attempt: Error: self signed certificate
 in certificate chain
npm ERR! fetch failed https://registry.npmjs.com/yargs-parser/-/yargs-parser-2.4
.1.tgz
npm WARN retry will retry, error on last attempt: Error: self signed certificate
 in certificate chain
npm ERR! fetch failed https://registry.npmjs.com/yargs-parser/-/yargs-parser-2.4
.1.tgz
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\494599.CTS.000\\
AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular2\npm-debug.log

**Comment by mrjmd** [comment]
Hi narasing, sorry you're having trouble. I am skeptical this error has anything to do with PDB, it looks like this is a lower level issue with either running node on windows or possibly specific to angular 2 packages with node on windows.

Either way, it's a bit out of scope for me to dig into debugging and I would suggest posting your issue to either the npm or angular repos.
