### ISSUE TITLE
Typings Issue on cloned repository

### ISSUE THREAD

**Issue by wpdildine** [mrjmd/pdb#91]
I'm getting lots of compiling errors...  I think this is related to duplicate copies of typings.

`generated/ng2_example_node/component.ts(4,13): error TS2304: Cannot find name '__moduleName'.
generated/ng2_example_node/component.ts(11,16): error TS2304: Cannot find name 'drupalSettings'.
generated/ng2_hero/component.ts(7,13): error TS2304: Cannot find name '__moduleName'.
generated/ng2_todo/component.ts(5,15): error TS2304: Cannot find name '__moduleName'.
`

Also, npm won't install on windows or linux without rolling back npm 2.x.x and making some changes to to the version numbers.  It works fine on mac.

**Comment by mrjmd** [comment]
The typing issues should all be resolved in the latest 8.x-1.x branch. Gulp compile now runs without any warnings.

Please open a separate issue for windows/linux npm if that is a problem that persists.
