### ISSUE TITLE
angular example not working

### ISSUE THREAD

**Issue by adrian-mitangi** [mrjmd/pdb#97]
Hi,

We've installed the pdb module and added the "NG2 Example" block.  We then did the npm install from the pdb_ng2 folder.

I "NG2 Example" title.   But that's about it.

Is there something that I didn't do that preventing the angular example to not work?

**Comment by mrjmd** [comment]
That should be all you need to do to have the example block working. To help you debug I will need more information about your setup.

- Are you running the latest 8.x-1.x branch of the module from github? Or how did you download / install the module? The latest alpha code on Drupal.org is a little behind.
- What version of Drupal 8 are you running?
- What do you see in your browser's console when you load the page with the example block? If you're seeing the blocks in the listing and are able to add one, that means Angular 2 should be attempting to bootstrap on the page where you see the title, but is failing for some reason. If you can provide the error in the console it will help us figure out why that might be.

**Comment by adrian-mitangi** [comment]
Hi @mrjmd,

I was able to figure out cause of the problem.  I had to disable "aggregate Javascript files" in the Performance screen when in development mode.

I'll also make sure to use the github version of pdb.
